server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:taskmanager.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
